spring:
  application:
    name: simple-authentication
  datasource:
    url: jdbc:postgresql://localhost:5432/SIMPLE_AUTH
    username: postgres
    password: t1ger
    hikari:
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
    show-sql: true
  mvc:
    path match:
      matching-strategy: ant-path-matcher
  jwt:
    secret-key: "092cc244-aea7-4bf3-a075-1f372baeed71"
    expiration-time: 300000  #5 Menit
  springfox:
    documentation:
      swagger:
        v2:
          path: /v2/api-docs

server:
  port: 8092
